@baseUrl = http://localhost:3000
@contentType = application/json

###create a book
POST {{baseUrl}}/books/create_book
Content-Type: {{contentType}}

{
  "title": "To kill a mockingbird 1",
  "author": "Scott Fitzgerald",
  "publication_year": 2000,
  "isbn": "9870789025",
  "description": "A novel about racial injustice",
  "user_id": 2
}

###Get all books

GET {{baseUrl}}/books/all_books

###Get books with pagination
GET {{baseUrl}}/books?page=1&limit=5

###search books with a specific term
GET {{baseUrl}}/books?searchTerm=great

###Filter books by year range
GET {{baseUrl}}/books?startYear=1920&endYear=2000

###Get book by ID
GET {{baseUrl}}/books/1

###Get book by ISBN
GET {{baseUrl}}/books/isbn/97808018601


###Get book by user
GET {{baseUrl}}/books/user/2

###Update a book
PUT {{baseUrl}}/books/update/16
Content-Type: {{contentType}}

{
  "title": "The Great Gatsby (Updated)",
  "description": "Updated description about the American Dream"
}

###Delete a book
DELETE {{baseUrl}}/books/delete/16
