@baseUrl = http://localhost:3000
@contentType = application/json


###Create a user

POST {{baseUrl}}/users/create_user
Content-Type: {{contentType}}

{
  "username": "tracywait",
  "email": "tracy@gmail.com",
  "password": "my_pass",
  "first_name": "Tracy",
  "last_name": "Wayatt"
}

###Get all users
GET {{baseUrl}}/users/all_users

###Get user by ID
GET {{baseUrl}}/users/id/4

###Get user by username
GET {{baseUrl}}/users/username/tracywait


###Update a user
PUT {{baseUrl}}/users/update/1
Content-Type: {{contentType}}

{
  "email": "john.updated@example.com",
  "first_name": "Johnny",
  "is_active": true
}

###delete a user
DELETE {{baseUrl}}/users/delete/1